set(OGREMAIN_SOURCES
    ${OGRE_SRC}/OgreMain/src/OgreAlignedAllocator.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAnimable.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAnimation.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAnimationState.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAnimationTrack.cpp
    ${OGRE_SRC}/OgreMain/src/OgreArchiveManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAutoParamDataSource.cpp
    ${OGRE_SRC}/OgreMain/src/OgreAxisAlignedBox.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBillboard.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBillboardChain.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBillboardParticleRenderer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBillboardSet.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBone.cpp
    ${OGRE_SRC}/OgreMain/src/OgreBorderPanelOverlayElement.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCamera.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCodec.cpp
    ${OGRE_SRC}/OgreMain/src/OgreColourValue.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCommon.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompiler2Pass.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositionPass.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositionTargetPass.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositionTechnique.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositor.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositorChain.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositorInstance.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositorManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositorScriptCompiler.cpp
    ${OGRE_SRC}/OgreMain/src/OgreCompositorSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreConfigFile.cpp
    ${OGRE_SRC}/OgreMain/src/OgreControllerManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreConvexBody.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDDSCodec.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDataStream.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDefaultHardwareBufferManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDefaultSceneQueries.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDynLib.cpp
    ${OGRE_SRC}/OgreMain/src/OgreDynLibManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreEdgeListBuilder.cpp
    ${OGRE_SRC}/OgreMain/src/OgreEntity.cpp
    ${OGRE_SRC}/OgreMain/src/OgreException.cpp
    ${OGRE_SRC}/OgreMain/src/OgreExternalTextureSource.cpp
    ${OGRE_SRC}/OgreMain/src/OgreExternalTextureSourceManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreFileSystem.cpp
    ${OGRE_SRC}/OgreMain/src/OgreFont.cpp
    ${OGRE_SRC}/OgreMain/src/OgreFontManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreFreeImageCodec.cpp
    ${OGRE_SRC}/OgreMain/src/OgreFrustum.cpp
    ${OGRE_SRC}/OgreMain/src/OgreGpuProgram.cpp
    ${OGRE_SRC}/OgreMain/src/OgreGpuProgramManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreGpuProgramUsage.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHardwareBufferManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHardwareIndexBuffer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHardwareOcclusionQuery.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHardwarePixelBuffer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHardwareVertexBuffer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHighLevelGpuProgram.cpp
    ${OGRE_SRC}/OgreMain/src/OgreHighLevelGpuProgramManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreImage.cpp
    ${OGRE_SRC}/OgreMain/src/OgreInstancedGeometry.cpp
    ${OGRE_SRC}/OgreMain/src/OgreKeyFrame.cpp
    ${OGRE_SRC}/OgreMain/src/OgreLight.cpp
    ${OGRE_SRC}/OgreMain/src/OgreLog.cpp
    ${OGRE_SRC}/OgreMain/src/OgreLogManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreManualObject.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMaterial.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMaterialManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMaterialSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMath.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMatrix3.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMatrix4.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMemoryAllocatedObject.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMemoryNedAlloc.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMemoryTracker.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMesh.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMeshManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMeshSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMeshSerializerImpl.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMovableObject.cpp
    ${OGRE_SRC}/OgreMain/src/OgreMovablePlane.cpp
    ${OGRE_SRC}/OgreMain/src/OgreNode.cpp
    ${OGRE_SRC}/OgreMain/src/OgreNumerics.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOptimisedUtil.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOptimisedUtilGeneral.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOptimisedUtilSSE.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOverlay.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOverlayContainer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOverlayElement.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOverlayElementCommands.cpp
    ${OGRE_SRC}/OgreMain/src/OgreOverlayManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePanelOverlayElement.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticle.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticleEmitter.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticleEmitterCommands.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticleIterator.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticleSystem.cpp
    ${OGRE_SRC}/OgreMain/src/OgreParticleSystemManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePass.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePatchMesh.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePatchSurface.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePixelFormat.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePlane.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePlatformInformation.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePolygon.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePose.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePrecompiledHeaders.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePredefinedControllers.cpp
    ${OGRE_SRC}/OgreMain/src/OgrePrefabFactory.cpp
    ${OGRE_SRC}/OgreMain/src/OgreProfiler.cpp
    ${OGRE_SRC}/OgreMain/src/OgreProgressiveMesh.cpp
    ${OGRE_SRC}/OgreMain/src/OgreQuaternion.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRectangle2D.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderQueue.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderQueueInvocation.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderQueueSortingGrouping.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderSystem.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderSystemCapabilities.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderSystemCapabilitiesManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderTarget.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderTexture.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderToVertexBuffer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRenderWindow.cpp
    ${OGRE_SRC}/OgreMain/src/OgreResource.cpp
    ${OGRE_SRC}/OgreMain/src/OgreResourceBackgroundQueue.cpp
    ${OGRE_SRC}/OgreMain/src/OgreResourceGroupManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreResourceManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRibbonTrail.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRoot.cpp
    ${OGRE_SRC}/OgreMain/src/OgreRotationSpline.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSceneManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSceneManagerEnumerator.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSceneNode.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSceneQuery.cpp
    ${OGRE_SRC}/OgreMain/src/OgreScriptCompiler.cpp
    ${OGRE_SRC}/OgreMain/src/OgreScriptLexer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreScriptParser.cpp
    ${OGRE_SRC}/OgreMain/src/OgreScriptTranslator.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSearchOps.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCameraSetup.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCameraSetupFocused.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCameraSetupLiSPSM.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCameraSetupPSSM.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowCaster.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowTextureManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSimpleRenderable.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSimpleSpline.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSkeleton.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSkeletonInstance.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSkeletonManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSkeletonSerializer.cpp
    ${OGRE_SRC}/OgreMain/src/OgreStaticGeometry.cpp
    ${OGRE_SRC}/OgreMain/src/OgreString.cpp
    ${OGRE_SRC}/OgreMain/src/OgreStringConverter.cpp
    ${OGRE_SRC}/OgreMain/src/OgreStringInterface.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSubEntity.cpp
    ${OGRE_SRC}/OgreMain/src/OgreSubMesh.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTagPoint.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTangentSpaceCalc.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTechnique.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTextAreaOverlayElement.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTexture.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTextureManager.cpp
    ${OGRE_SRC}/OgreMain/src/OgreTextureUnitState.cpp
    ${OGRE_SRC}/OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp
    ${OGRE_SRC}/OgreMain/src/OgreUserDefinedObject.cpp
    ${OGRE_SRC}/OgreMain/src/OgreVector2.cpp
    ${OGRE_SRC}/OgreMain/src/OgreVector3.cpp
    ${OGRE_SRC}/OgreMain/src/OgreVector4.cpp
    ${OGRE_SRC}/OgreMain/src/OgreVertexIndexData.cpp
    ${OGRE_SRC}/OgreMain/src/OgreViewport.cpp
    ${OGRE_SRC}/OgreMain/src/OgreWindowEventUtilities.cpp
    ${OGRE_SRC}/OgreMain/src/OgreWireBoundingBox.cpp
    ${OGRE_SRC}/OgreMain/src/OgreZip.cpp
    ${OGRE_SRC}/OgreMain/src/WIN32/OgreConfigDialog.cpp
    ${OGRE_SRC}/OgreMain/src/WIN32/OgreErrorDialog.cpp
    ${OGRE_SRC}/OgreMain/src/WIN32/OgreTimer.cpp
    ${OGRE_SRC}/OgreMain/src/WIN32/OgreWin32Resources.rc
)
set(RENDERSYSTEM_GL_SOURCES
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLExtSupport.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLGpuProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgramManager.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLPreprocessor.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/GLSL/src/OgreGLSLProgramFactory.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLATIFSInit.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLContext.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLDefaultHardwareBufferManager.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLEngineDll.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLFBOMultiRenderTarget.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLFBORenderTexture.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLFrameBufferObject.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLGpuNvparseProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLGpuProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLGpuProgramManager.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLHardwareBufferManager.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLHardwareIndexBuffer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLHardwareOcclusionQuery.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLHardwarePixelBuffer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLPBRenderTexture.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLPixelFormat.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLPlugin.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLRenderSystem.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLRenderTexture.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLRenderToVertexBuffer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLSupport.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLTexture.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreGLTextureManager.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreWin32GLSupport.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreWin32RenderTexture.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/OgreWin32Window.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/atifs/src/ATI_FS_GLGpuProgram.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/atifs/src/Compiler2Pass.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/atifs/src/ps_1_4.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/glew.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_ps1.0_lexer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_ps1.0_parser.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_rc1.0_lexer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_rc1.0_parser.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_ts1.0_lexer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_ts1.0_parser.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_vs1.0_lexer.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/_vs1.0_parser.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/avp1.0_impl.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/nvparse.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/nvparse_errors.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/ps1.0_program.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/rc1.0_combiners.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/rc1.0_final.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/rc1.0_general.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/ts1.0_inst.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/ts1.0_inst_list.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/vcp1.0_impl.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/vp1.0_impl.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/vs1.0_inst.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/vs1.0_inst_list.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/nvparse/vsp1.0_impl.cpp
    ${OGRE_SRC}/RenderSystems/GL/src/win32/OgreWin32Context.cpp
)
set(PLUGIN_OCTREE_SOURCES
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreHeightmapTerrainPageSource.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctree.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreeCamera.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreeNode.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreePlugin.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreeSceneManager.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreeSceneManagerDll.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreOctreeSceneQuery.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreTerrainPage.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreTerrainPageSource.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreTerrainRenderable.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreTerrainSceneManager.cpp
    ${OGRE_SRC}/PlugIns/OctreeSceneManager/src/OgreTerrainVertexProgram.cpp
)
set(PLUGIN_CG_SOURCES
    ${OGRE_SRC}/PlugIns/CgProgramManager/src/OgreCgPlugin.cpp
    ${OGRE_SRC}/PlugIns/CgProgramManager/src/OgreCgProgram.cpp
    ${OGRE_SRC}/PlugIns/CgProgramManager/src/OgreCgProgramFactory.cpp
    ${OGRE_SRC}/PlugIns/CgProgramManager/src/OgreCgProgramManagerDll.cpp
)
